### ISSUE TITLE
importing doesn't work on Python 3 

### ISSUE THREAD

**Issue by misingnoglic** [IndicoDataSolutions/IndicoIo-python#206]
When importing the package, I get this error

> import indicoio
> Traceback (most recent call last):
> File "", line 1, in 
> File "C:\Program Files\Python35\lib\site-packages\indicoio__init__.py", line 13, in 
> from indicoio.text.twitter_engagement import twitter_engagement
> File "C:\Program Files\Python35\lib\site-packages\indicoio\text\twitter_engagement.py", line 1, in 
> from indicoio.utils.api import api_handler
> File "C:\Program Files\Python35\lib\site-packages\indicoio\utils\api.py", line 10, in 
> import urlparse
> ImportError: No module named 'urlparse'

I just submitted a pull request to fix this.

**Comment by sihrc** [comment]
Resolved in #203
