### ISSUE TITLE
Load images from file or url

### ISSUE THREAD

**Issue by madisonmay** [IndicoDataSolutions/IndicoIo-python#22]
Add support for using filenames or urls in place of numpy arrays for our image APIs.  Should go a long way towards making our image APIs more pleasant to use.

**Comment by Slater-Victoroff** [comment]
This shouldn't be on the client side. Putting this on the client-side of the library makes everything worse and nothing better. This NEEDS to be on the server side, which isn't actually in this repository. I'll put this functionality in on the server-side, but I'm closing this.

**Comment by madisonmay** [comment]
Loading files from a filepath requires modification of client side code (since the server actually doesn't have access to the files).  Loading files from urls likewise requires modification of client side code even if the url fetch happens on the server, because I think `image_preprocess` will raise an error on strings (so the request will never get made).

**Comment by madisonmay** [comment]
Filepath support has been added, URL support is open as a PR.
