### ISSUE TITLE
Bundle `imagefeatures` API with Sklearn Classifier / Regressor

### ISSUE THREAD

**Issue by madisonmay** [IndicoDataSolutions/IndicoIo-python#23]
Bundling our imagefeatures API with a scikit-learn Classifier / Regressor would enable people to quickly prototype image classification problems with minimal effort.  I think this is crucial to making our imagefeatures API actually usable.

**Comment by madisonmay** [comment]
Theano-based classifiers / regressors would also do the trick, although I think scikit-learn may be a better bet for this use case thanks to good error messages, CV, etc.

**Comment by madisonmay** [comment]
This might make for a enjoyable project @gwulfs -- don't feel like you have to take this on if you don't want to, but I think it might be up your alley.  Happy to provide more details if you have an interest.

**Comment by gwulfs** [comment]
lets chat about it tmrw

**Comment by Slater-Victoroff** [comment]
Want to hear a resolution on this. I can bang this out tonight if @gwulfs isn't already planning on pushing this soon.

**Comment by gwulfs** [comment]
@Slater-Victoroff did anything become of this?

**Comment by Slater-Victoroff** [comment]
@gwulfs not yet, but I might have some spare time in the next day or so to bang this out. I think there's a definite use case even if it's not large, and I want to dip our toes into figuring out the best way to interface with general open source projects.
