### ISSUE TITLE
Transparency of image preprocessing

### ISSUE THREAD

**Issue by madisonmay** [IndicoDataSolutions/IndicoIo-python#26]
```bash
>>> import this

...
Explicit is better than implicit.
...
```

Image preprocessing is currently not all transparent.  If users pass in oddly shaped images they might be surprised to find that performance is poor.  By exposing a more transparent interface for image preprocessing we cut down on the number of surprises.

**Comment by Slater-Victoroff** [comment]
+1

**Comment by dianavermilya** [comment]
resolved in #78
