### ISSUE TITLE
Insecure platform warning

### ISSUE THREAD

**Issue by Slater-Victoroff** [IndicoDataSolutions/IndicoIo-python#43]
https://urllib3.readthedocs.org/en/latest/security.html

**Comment by madisonmay** [comment]
We can use a patch provided by pyopenssl if the user has that package installed: https://urllib3.readthedocs.org/en/latest/security.html#openssl-pyopenssl

**Comment by madisonmay** [comment]
Pseudocode:
```
if not open_ssl_context_available():
    try:
        apply_pyopenssl_patch()
    except ImportError:
        silence_warning()
        raise_indico_warning()
```
