### ISSUE TITLE
Wheel files

### ISSUE THREAD

**Issue by madisonmay** [IndicoDataSolutions/IndicoIo-python#90]
Investigate using wheels for blazing fast python lib installs.

**Comment by sihrc** [comment]
Is that just 
```
pip install wheel
pip wheel --wheel-dir=/local/wheels -r requirements.txt
pip install --no-index --find-links=/local/wheels -r requirements.txt
```

The dependencies we use are already supported. 

Also, is it just me or does wheel look weirdly spelled
