### ISSUE TITLE
Content Filtering resize

### ISSUE THREAD

**Issue by Newmu** [IndicoDataSolutions/IndicoIo-python#91]
Since we use 128 px internally, a min resize on the client side to this will save bandwidth/improve response time.

**Comment by Newmu** [comment]
Also requires support for resizing minimum axis to a specific size as the api works on/expects/takes advantage of non-square crops.

**Comment by madisonmay** [comment]
:+1: thanks for opening the issue!  Hope to get around to this soon.

**Comment by dianavermilya** [comment]
Added in d00b669a16279b12433918181dd56bd9d6cb579a
